import { WRBTC_SEPOLIA_ADDRESS, SEPOLIA_BRIDGE_ADDRESS, ROOTSTOCK_BRIDGE_ADDRESS } from './addresses'
import WRBTC_ABI from './abiFiles/WRBTC.json'
import SEPOLIA_BRIDGE_ABI from './abiFiles/SepoliaBridge.json'
import ROOTSTOCK_BRIDGE_ABI from './abiFiles/RootStackBridge.json'

export {
  WRBTC_SEPOLIA_ADDRESS,
  SEPOLIA_BRIDGE_ADDRESS,
  ROOTSTOCK_BRIDGE_ADDRESS,
  WRBTC_ABI,
  SEPOLIA_BRIDGE_ABI,
  ROOTSTOCK_BRIDGE_ABI,
}
